### PR TITLE
CSV Namespace and Plugins

### PR DESCRIPTION
**Pull request by pbronez**
Here's an initial shim for #6 

Please confirm that I've got this started properly. I think the template file should be good to go.

The tool itself is just a renamed clone from the `network` name space. I plan to write a tool that parses the CSV and pushes out each row as a message to RabbitMQ.

### CODE REVIEW

**Comment by cglewis** [comment]
@pbronez structure and template looks great.  just update the app and dockerfile for the specific of csv as you mention and should be good to go.  thanks!

**Comment by cglewis** [comment]
@pbronez looks good, is this ready to go, or still in progress?

**Comment by pbronez** [comment]
Should be feature-complete, but haven't tested it yet. I pushed up to my fork so I could load it into my local vent instance. I'll ping you when I've confirmed it actually runs.

**Comment by cglewis** [comment]
as an aside, once this is merged, it would probably be a good idea to update this: https://github.com/CyberReboot/vent/blob/master/README.md to be more inclusive than just PCAPs.

**Comment by pbronez** [comment]
Per #26 , new plugins need to be on the Master Branch. I'll create a new PR.

**Pull request closed without merging**
